### ISSUE TITLE
Data Loaded Animation

### ISSUE THREAD

**Issue by xxu511** [SOFTENG310-TEAM-3/MunchMatch#23]
**What is your feature?**
Adding the loading content when user click the button

**Why is this feature needed?**
Because without this animation the user would see the blank of the card

**Who is your feature for?**
to make the user more engagement 

**Additional context**
This is for use to feel more engagement in to the app so the user would not just wait to see the blank

**Comment by tanagrams** [comment]
closed with pr #22
